spring:
  application:
    name: sport-club-management
  flyway:
    enabled: false
    locations: db/migration
    baseline-on-migrate: true
    out-of-order: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      jakarta.persistence.schema-generation.create-source: metadata
      jakarta.persistence.schema-generation.scripts.action: create
      jakarta.persistence.schema-generation.scripts.create-target: src/main/resources/db/migration/create-ddl.sql
      hibernate.hbm2ddl.delimiter: ;
  h2:
    console:
      enabled: true
server:
  port: 8082
feature:
  updateClubEnabled: false
  getAllClubDetailsByFilter: false